name: Generate Daily German Content

on:
  schedule:
    # ドイツ時間5時/6時
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  generate-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install anthropic

    - name: Generate German content
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python generate_content.py

    - name: Commit and push new content
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "German Content Generator"

        # Pull latest changes first to avoid conflicts
        git pull --rebase origin main || true

        git add blog/ data/

        if git diff --staged --quiet; then
          echo "No new content to commit"
        else
          COMMIT_MSG="Add A2 German content $(date +%Y-%m-%d) - Focus on vocabulary diversity"
          if [ $(date +%u) -eq 7 ]; then
            COMMIT_MSG="$COMMIT_MSG + weekly vocabulary summary"
          fi
          git commit -m "$COMMIT_MSG [skip ci]"

          # Try to push, with retry logic
          for i in {1..3}; do
            if git push; then
              echo "Push successful on attempt $i"
              break
            else
              echo "Push failed on attempt $i, pulling and retrying..."
              git pull --rebase origin main || true
              sleep 2
            fi
          done
        fi