name: Generate Daily German Content (Simple)

on:
  schedule:
    # 毎日午前9時（UTC）に実行 = 日本時間18時、ドイツ時間10時/11時
    - cron: '0 9 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  generate-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install anthropic

    - name: Generate German content
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python generate_content.py

    - name: Commit and push new content
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "German Content Generator"
        git add blog/ data/

        if git diff --staged --quiet; then
          echo "No new content to commit"
        else
          COMMIT_MSG="Add A2 German content $(date +%Y-%m-%d) - Focus on vocabulary diversity"
          if [ $(date +%u) -eq 7 ]; then
            COMMIT_MSG="$COMMIT_MSG + weekly vocabulary summary"
          fi
          git commit -m "$COMMIT_MSG [skip ci]"
          git push
        fi